[project]
name = "ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-search-results>=2.4.2",
    "langchain>=0.3.27",
    "langchain-openai>=0.3.30",
    "openai>=1.99.9",
    "python-dotenv>=1.1.1",
]
